Update dependencies
saleor/saleor-app-sdk pull request #279
Opened 2023-08-24 14:20 UTC by lkostrowski

2023-08-25 09:35 UTC, krzysztofwolski requested changes
No issues with the code, but the tests are failing.

2023-08-29 08:27 UTC, lkostrowski commented
Locally tests pass, I can't reproduce it locally :(

2023-08-29 08:46 UTC, lkostrowski commented
@krzysztofwolski fixed. I updated pnpm lock for pnpm@8 but github actions were using pnpm@7

2023-08-29 10:25 UTC, krzysztofwolski approved these changes

2023-08-29 11:41 UTC, merged