Encrypted metadata
saleor/saleor-app-sdk pull request #84
Opened 2022-10-14 14:04 UTC by krzysztofwolski

Closes #83

Extend settings manager with encryption methods.

2022-10-14 14:55 UTC, lkostrowski requested changes
Breaking SRP - lets split to 2 implementations of SettingsManager

2022-10-14 14:55 UTC, lkostrowski commented on src/settings-manager/metadata-manager.test.ts
> +    });
if metadata manager doesnt force encryption, we should not require encryption key, if someone will not use encryption

So I think its better to write it this way, WDYT

```
interface SettingsManager {
set(...);
get(...)
} 

class MetadataManager implements SettingsManager {} // or PlainMetadataManager

class EncryptedMetadataManager implements SettingsManager {} 

```

I think its quite clean

2022-10-14 14:55 UTC, lkostrowski commented
@zaiste please check encryption impl

2022-10-17 10:06 UTC, zaiste approved these changes

2022-10-18 11:17 UTC, lkostrowski approved these changes

2022-10-18 11:38 UTC, merged